apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-account
  template:
    metadata:
      labels:
        app: service-account
    spec:
      containers:
        - name: service-account
          image: service_account:v1.0
          ports:
            - containerPort: 3000 # port service-account yang ada di image docker
---
apiVersion: v1
kind: Service
metadata:
  name: service-account
spec:
  selector:
    app: service-account
  ports:
    - protocol: TCP
      port: 80 # Port yang digunakan di dalam cluster
      targetPort: 3000 # Port di container yang ditargetkan
      # nodePort: 30001  # Port yang digunakan untuk mengakses dari luar cluster
  type: ClusterIP # Tipe layanan untuk expose port ke luar cluster
